packages:
  - "backend"
  - "contracts"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: false
  esbuild: false
  msgpackr-extract: false
  prisma: true
  unrs-resolver: false
