version: '3.8'

services:
  proof-server:
    image: midnightntwrk/proof-server:8.0.3
    command: ['midnight-proof-server', '-v']
    container_name: "proof-server-local"
    ports:
      - '6300:6300'